name: Build Packages

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  push:
    tags: ["*"]
# Matrix



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deb-version:
          - bullseye
          - buster
          - bookworm
          - focal
          - groovy
          - hirsute
          - trusty
    steps:
    - uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
      id: go
    - name: Goreleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
    
    - name: Push to package repository
      env:
        HOGLANDET_DEB_USER: ${{ secrets.HOGLANDET_DEB_USER }}
        HOGLANDET_DEB_KEY: ${{ secrets.HOGLANDET_DEB_KEY }}
        HOGLANDET_DEB_URL: ${{ secrets.HOGLANDET_DEB_URL }}
        DEB_VERSION: ${{ matrix.deb-version }}
      run: |
        echo "Pushing to package repository"
        cd dist
        for file in ./*.deb; do
          echo "Uploading $file"
          curl --user "${HOGLANDET_DEB_USER}:${HOGLANDET_DEB_KEY}" --upload-file $file "${HOGLANDET_DEB_URL}/${DEB_VERSION}/main/upload"
  
    