name: Build Packages

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  push:
    tags: ["*"]
# Matrix



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
      id: go
    - name: Goreleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: ${{ github.event.release.tag.name }}
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist/**

  publish-debian:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deb-version:
          - stable
          - unstable
          - bookworm
          - bullseye
          - noble
          - mantic
          - focal
          - jammy
          - lunar
    steps:
      - uses: actions/download-artifact@v4
      - name: Find files
        id: Find
        run: |
          {
            echo 'FILELIST<<EOF'
            find . -name '*.deb' -type f -print
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Push to package repository
        env:
          HOGLANDET_DEB_USER: ${{ secrets.HOGLANDET_DEB_USER }}
          HOGLANDET_DEB_KEY: ${{ secrets.HOGLANDET_DEB_KEY }}
          HOGLANDET_DEB_URL: ${{ secrets.HOGLANDET_DEB_URL }}
          DEB_VERSION: ${{ matrix.deb-version }}
        run: |
          for file in $FILELIST; do
            echo "Uploading $file to ${HOGLANDET_DEB_URL}/${DEB_VERSION}/main/upload"
            curl --user "${HOGLANDET_DEB_USER}:${HOGLANDET_DEB_KEY}" --upload-file "$file" "${HOGLANDET_DEB_URL}/${DEB_VERSION}/main/upload"
          done
  
  publish-alpine:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Find files
        id: Find
        run: |
          {
            echo 'FILELIST<<EOF'
            find . -name '*.apk' -type f -print
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Push to package repository (any)
        env:
          HOGLANDET_DEB_USER: ${{ secrets.HOGLANDET_DEB_USER }}
          HOGLANDET_DEB_KEY: ${{ secrets.HOGLANDET_DEB_KEY }}
          HOGLANDET_APK_URL: ${{ secrets.HOGLANDET_APK_URL }}
        run: |
          for file in $FILELIST; do
            echo "Uploading $file to ${HOGLANDET_APK_URL}"
            curl --user "${HOGLANDET_DEB_USER}:${HOGLANDET_DEB_KEY}" --upload-file "$file" "${HOGLANDET_APK_URL}"
          done