name: Build Packages

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  push:
    tags: ["*"]
# Matrix



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
      id: go
    - name: Goreleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: ${{ github.event.release.tag.name }}
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist/**

  publish-packages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Find DEB files
        id: find-deb
        run: |
          {
            echo 'DEB_FILELIST<<EOF'
            find . -name '*.deb' -type f -print
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: Find APK files
        id: find-apk
        run: |
          {
            echo 'APK_FILELIST<<EOF'
            find . -name '*.apk' -type f -print
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: Find RPM files
        id: find-rpm
        run: |
          {
            echo 'RPM_FILELIST<<EOF'
            find . -name '*.rpm' -type f -print
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: Push DEB files
        env:
          HOGLANDET_DEB_USER: ${{ secrets.HOGLANDET_DEB_USER }}
          HOGLANDET_DEB_KEY: ${{ secrets.HOGLANDET_DEB_KEY }}
          HOGLANDET_DEB_URL: ${{ secrets.HOGLANDET_DEB_URL }}
        run: |
          for file in $DEB_FILELIST; do
            echo "Uploading $file to ${HOGLANDET_DEB_URL}/stable/main/upload"
            curl --user "${HOGLANDET_DEB_USER}:${HOGLANDET_DEB_KEY}" --upload-file "$file" "${HOGLANDET_DEB_URL}"
          done
      
      - name: Push APK files
        env:
          HOGLANDET_DEB_USER: ${{ secrets.HOGLANDET_DEB_USER }}
          HOGLANDET_DEB_KEY: ${{ secrets.HOGLANDET_DEB_KEY }}
          HOGLANDET_APK_URL: ${{ secrets.HOGLANDET_APK_URL }}
        run: |
          for file in $APK_FILELIST; do
            echo "Uploading $file to ${HOGLANDET_APK_URL}"
            curl --user "${HOGLANDET_DEB_USER}:${HOGLANDET_DEB_KEY}" --upload-file "$file" "${HOGLANDET_APK_URL}"
          done
      
      - name: Push RPM files
        env:
          HOGLANDET_DEB_USER: ${{ secrets.HOGLANDET_DEB_USER }}
          HOGLANDET_DEB_KEY: ${{ secrets.HOGLANDET_DEB_KEY }}
          HOGLANDET_RPM_URL: ${{ secrets.HOGLANDET_RPM_URL }}
        run: |
          for file in $RPM_FILELIST; do
            echo "Uploading $file to ${HOGLANDET_APK_URL}"
            curl --user "${HOGLANDET_DEB_USER}:${HOGLANDET_DEB_KEY}" --upload-file "$file" "${HOGLANDET_RPM_URL}"
          done